### ISSUE TITLE
2 packages - one with IServerTiming , one with asp.net core middleware

### ISSUE THREAD

**Issue by ignatandrei** [tpeczek/Lib.AspNetCore.ServerTiming#19]
I want to add timings toan assembly. But I do not want to add the whole middleware to the project ( the middleware should be just into the ASP.NET Core  )  -  I want just to have reference to IServerTiming .
Could you separate into 2 nuget packages ?

**Comment by tpeczek** [comment]
Hi @ignatandrei,

Yes, this makes sense. The trick is that this will be a breaking change. So before I do this, I'll wrap up and release #16. Than I can do this and #10.

**Comment by ignatandrei** [comment]
Ok. Let me know. And thanks

**Comment by tpeczek** [comment]
[Lib.AspNetCore.ServerTiming.Abstractions](https://www.nuget.org/packages/Lib.AspNetCore.ServerTiming.Abstractions/) package is now available.

**Comment by ignatandrei** [comment]
Thanks

**Comment by tpeczek** [comment]
Ok, something messed up during CI/CD (#22), it will be another day or two.

**Comment by tpeczek** [comment]
Should be ok now.

**Comment by ignatandrei** [comment]
TimeAction and TimeTask -could be on the same dll ?

**Comment by tpeczek** [comment]
Hmm, I'll need to think if/how they fit.
