### ISSUE TITLE
On integration test runs, context.RequestServices can be null.

### ISSUE THREAD

**Issue by ChaosEngine** [tpeczek/Lib.AspNetCore.ServerTiming#4]
https://github.com/tpeczek/Lib.AspNetCore.ServerTiming/blob/85794b22699d56730de0dad180b41760e23ebae9/Lib.AspNetCore.ServerTiming/ServerTimingMiddleware.cs#L74

On integration test runs, `context.RequestServices` can be null. Suggesting null check

```
private void HandleServerTiming(HttpContext context)
{
    context.Response.OnStarting(() => {
		if (context.RequestServices != null)
		{
			IServerTiming serverTiming = context.RequestServices.GetRequiredService<IServerTiming>();

			if (serverTiming.Metrics.Count > 0)
			{
				context.Response.SetServerTiming(new ServerTimingHeaderValue(serverTiming.Metrics));
			}
		}
        return _completedTask;
    });
}
```

**Comment by tpeczek** [comment]
Hi @ChaosEngine,

I must say I have mixed feelings about this. Adding this null check would result in middleware having different behavior in integration test and in production, which is rather unexpected.

Quick search through ASP.NET Core source code also shows that generally there are no null checks around accessing this property and all relevant tests make sure it's properly arranged.

This makes me think it might not be the way to go.

**Comment by ChaosEngine** [comment]
Well I must agree with those arguments.
How about using the official [DI solution for middlewares](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?tabs=aspnetcore2x#per-request-dependencies) and use DI to inject IServerTiming serverTiming
```
#region Methods
/// <summary>
/// Process an individual request.
/// </summary>
/// <param name="context">The context.</param>
/// <param name="serverTiming">service injected interface</param>
/// <returns>The task object representing the asynchronous operation.</returns>
public Task Invoke(HttpContext context, IServerTiming serverTiming)
{
    if (_timingAllowOriginHeaderValue != null)
    {
        context.Response.SetResponseHeader(HeaderNames.TimingAllowOrigin, _timingAllowOriginHeaderValue);
    }

    HandleServerTiming(context, serverTiming);

    return _next(context);
}

private void HandleServerTiming(HttpContext context, IServerTiming serverTiming)
{
    context.Response.OnStarting(() => {
		if (serverTiming.Metrics.Count > 0)
		{
			context.Response.SetServerTiming(new ServerTimingHeaderValue(serverTiming.Metrics));
		}
        return _completedTask;
    });
}
#endregion
```

**Comment by tpeczek** [comment]
Yes I was considering that yesterday. The only thing I don't like about it is that it will be a breaking change, but I guess I should bite the bullet.

**Comment by ChaosEngine** [comment]
I could write a sample project exposing faulty behavior with integration tests.

**Comment by tpeczek** [comment]
I'm happy with pull requests :). I don't have a contributing guidelines around (never enough time for the organizational stuff), but you can take a look [here](https://github.com/tpeczek/Lib.Net.Http.EncryptedContentEncoding) to see what naming conventions I tend to keep in my repositories (my apologies for the inconvenient form).
